<?php

declare(strict_types=1);

return [
    'locale' => env('NUEWIRE_INSTALLER_LOCALE', 'id'),
    'composer_binary' => env('NUEWIRE_COMPOSER_BINARY'),

    'github' => [
        'api_url' => env('NUEWIRE_GITHUB_API_URL', 'https://api.github.com'),
        'owner' => env('NUEWIRE_GITHUB_OWNER', 'nuewire'),
        'token' => env('NUEWIRE_GITHUB_TOKEN'),
        'timeout' => (int) env('NUEWIRE_GITHUB_TIMEOUT', 10),
        // Optional package => owner/repository overrides.
        'repositories' => [],
    ],

    'ui' => [
        'enabled' => (bool) env('NUEWIRE_INSTALLER_UI', true),
        'allow_updates' => (bool) env('NUEWIRE_INSTALLER_UI_ALLOW_UPDATES', true),
        'allowed_environments' => ['local'],
        'process_timeout' => 600,
        'authorization' => [
            'require_authenticated_user' => true,
            'gate' => env('NUEWIRE_INSTALLER_UI_GATE'),
            'guard' => env('NUEWIRE_INSTALLER_UI_GUARD'),
        ],
    ],

    'manager' => [
        'package' => 'nuewire/installer',
        'label' => ['id' => 'Installer', 'en' => 'Installer'],
        'description' => ['id' => 'Instalasi dan pembaruan package.', 'en' => 'Package installation and updates.'],
        'order' => 0,
    ],

    'core_packages' => [
        'support' => [
            'package' => 'nuewire/support',
            'constraint' => '^1.0',
            'label' => ['id' => 'Support', 'en' => 'Support'],
            'description' => ['id' => 'Helper dan fondasi package.', 'en' => 'Shared package helpers.'],
            'order' => 5,
        ],
    ],

    'remote_catalog' => [
        'enabled' => (bool) env('NUEWIRE_CATALOG_ENABLED', false),
        'url' => env('NUEWIRE_CATALOG_URL'),
        'public_key' => env('NUEWIRE_CATALOG_PUBLIC_KEY'),
        'timeout' => (int) env('NUEWIRE_CATALOG_TIMEOUT', 5),
    ],

    'features' => [
        'platform' => [
            'package' => 'nuewire/platform',
            'constraint' => '^2.1',
            'label' => ['id' => 'Platform', 'en' => 'Platform'],
            'description' => ['id' => 'Layout dan navigasi admin.', 'en' => 'Admin layout and navigation.'],
            'recommended' => true,
            'order' => 10,
        ],
        'users' => [
            'package' => 'nuewire/users',
            'constraint' => '^1.0',
            'label' => ['id' => 'Pengguna', 'en' => 'Users'],
            'description' => ['id' => 'Pengguna dan aktivitas login.', 'en' => 'Users and login activity.'],
            'recommended' => true,
            'requires_features' => ['platform'],
            'setup_command' => 'nuewire:users:install',
            'order' => 15,
        ],
        'acl' => [
            'package' => 'nuewire/acl',
            'constraint' => '^1.0',
            'label' => ['id' => 'ACL', 'en' => 'ACL'],
            'description' => ['id' => 'Role dan permission.', 'en' => 'Roles and permissions.'],
            'recommended' => false,
            'requires_features' => ['users'],
            'setup_command' => 'nuewire:acl:install',
            'order' => 18,
        ],
        'filesystem' => [
            'package' => 'nuewire/filesystem',
            'constraint' => '^1.0',
            'label' => ['id' => 'Filesystem', 'en' => 'Filesystem'],
            'description' => ['id' => 'Local, S3, dan Bunny CDN.', 'en' => 'Local, S3, and Bunny CDN.'],
            'recommended' => true,
            'order' => 20,
        ],
        'mail' => [
            'package' => 'nuewire/mail',
            'constraint' => '^1.0',
            'label' => ['id' => 'Email', 'en' => 'Mail'],
            'description' => ['id' => 'SMTP, Resend, SES, dan lainnya.', 'en' => 'SMTP, Resend, SES, and more.'],
            'recommended' => true,
            'order' => 30,
        ],
        'hero' => [
            'package' => 'nuewire/hero',
            'constraint' => '^1.0',
            'label' => ['id' => 'Hero', 'en' => 'Hero'],
            'description' => ['id' => 'Hero website dengan media, CTA, dan urutan tampilan.', 'en' => 'Website hero content with media, calls to action, and ordering.'],
            'recommended' => false,
            'requires_features' => ['platform', 'filesystem', 'logs'],
            'setup_command' => 'nuewire:hero:install',
            'order' => 33,
        ],
        'banner' => [
            'package' => 'nuewire/banner',
            'constraint' => '^1.0',
            'label' => ['id' => 'Banner', 'en' => 'Banner'],
            'description' => ['id' => 'Banner gambar dan tautan website.', 'en' => 'Website image banners and destination links.'],
            'recommended' => false,
            'requires_features' => ['platform', 'filesystem', 'logs'],
            'setup_command' => 'nuewire:banner:install',
            'order' => 34,
        ],
        'page' => [
            'package' => 'nuewire/page',
            'constraint' => '^1.0',
            'label' => ['id' => 'Halaman', 'en' => 'Pages'],
            'description' => ['id' => 'Kelola halaman statis website.', 'en' => 'Manage static website pages.'],
            'recommended' => true,
            'requires_features' => ['platform'],
            'setup_command' => 'nuewire:page:install',
            'order' => 35,
        ],
        'unduhan' => [
            'package' => 'nuewire/unduhan',
            'constraint' => '^1.0',
            'label' => ['id' => 'Unduhan', 'en' => 'Downloads'],
            'description' => ['id' => 'Kategori dan dokumen unduhan dengan archive serta revision history.', 'en' => 'Download categories and documents with archive and revision history.'],
            'recommended' => false,
            'requires_features' => ['platform', 'filesystem', 'logs'],
            'setup_command' => 'nuewire:unduhan:install',
            'order' => 36,
        ],
        'media' => [
            'package' => 'nuewire/media',
            'constraint' => '^1.0',
            'label' => ['id' => 'Media', 'en' => 'Media'],
            'description' => ['id' => 'Album dan file media dengan Archive serta revision history.', 'en' => 'Media albums and files with Archive and revision history.'],
            'recommended' => false,
            'requires_features' => ['platform', 'filesystem', 'logs'],
            'setup_command' => 'nuewire:media:install',
            'order' => 37,
        ],
        'newsletter' => [
            'package' => 'nuewire/newsletter',
            'constraint' => '^1.0',
            'label' => ['id' => 'Newsletter', 'en' => 'Newsletter'],
            'description' => ['id' => 'Subscriber dan broadcast email terjadwal.', 'en' => 'Subscribers and scheduled email broadcasts.'],
            'recommended' => false,
            'requires_features' => ['platform', 'mail'],
            'setup_command' => 'nuewire:newsletter:install',
            'order' => 38,
        ],
        'logs' => [
            'package' => 'nuewire/logs',
            'constraint' => '^1.0',
            'label' => ['id' => 'Log Platform', 'en' => 'Platform Logs'],
            'description' => ['id' => 'Audit trails, request logs, dan system logs.', 'en' => 'Audit trails, request logs, and system logs.'],
            'recommended' => true,
            'requires_features' => ['platform'],
            'setup_command' => 'nuewire:logs:install',
            'order' => 40,
        ],
        'backup' => [
            'package' => 'nuewire/backup',
            'constraint' => '^1.0',
            'label' => ['id' => 'Backup', 'en' => 'Backup'],
            'description' => ['id' => 'Backup database dan file storage.', 'en' => 'Database and file-storage backups.'],
            'recommended' => true,
            'requires_features' => ['platform', 'filesystem'],
            'setup_command' => 'nuewire:backup:install',
            'order' => 45,
        ],
        'cache' => [
            'package' => 'nuewire/cache',
            'constraint' => '^1.0',
            'label' => ['id' => 'Cache', 'en' => 'Cache'],
            'description' => ['id' => 'Pembersihan cache Laravel dan permission.', 'en' => 'Laravel and permission cache clearing.'],
            'recommended' => true,
            'requires_features' => ['platform'],
            'setup_command' => 'nuewire:cache:install',
            'order' => 47,
        ],
    ],
];
